### PR TITLE
Fix 400 error when creating notes in "All notes" view

### LINKED ISSUE #159: Creating notes from "All notes" view fails with "Content and board ID are required" error
### What

When viewing the "All notes" page (/boards/all-notes) and clicking the "Create new note" button, the request fails with a 400 error stating "Content and board ID are required", even though the board ID is being sent in the request.

Steps to Reproduce

  1. Navigate to the "All notes" view at /boards/all-notes
  2. Click the pencil/create button to add a new note
  3. The request fails with error: {"error":"Content and board ID are required"}

Image

### Why

  The /api/boards/all-notes/notes POST endpoint has stricter validation than the regular board endpoint. It checks:
  if (!content || !boardId) {
    return NextResponse.json({ error: "Content and board ID are required" }, { status: 400 })
  }

  Since content is an empty string "" (which is falsy), the validation fails. The regular board endpoint at
  /api/boards/[id]/notes doesn't validate content, allowing empty notes to be created.

 ### Proposed Fix

  Update the validation in /app/api/boards/all-notes/notes/route.ts to only require boardId:
  // Only boardId is required for all-notes endpoint
  if (!boardId) {
    return NextResponse.json({ error: "Board ID is required" }, { status: 400 })
  }

...

### PR DESCRIPTION
**Pull request by Nalin-khanna**
Fix note creation in "All notes" view
Updated the notes API call to always use actualTargetBoardId instead of "all-notes", resolving the 400 error when creating notes from the All notes page.

fixes #159

### CODE REVIEW

File: app/boards/[id]/page.tsx [hunk 1]
```diff
@@ -786,7 +786,7 @@ export default function BoardPage({
       const isAllNotesView = boardId === "all-notes";
 
       const response = await fetch(
-        `/api/boards/${isAllNotesView ? "all-notes" : actualTargetBoardId}/notes`,
+        `/api/boards/${actualTargetBoardId}/notes`,
```
Comment (slavingia) [inline app/boards/[id]/page.tsx:789]: Which board is selected for the addition?

Comment (Nalin-khanna) [reply app/boards/[id]/page.tsx]: The board selected is the last one added by the user. The issue was with the API endpoint , I’ve fixed it and added an E2E spec for adding notes in the All Notes view.

**Comment by Nalin-khanna** [comment]
@slavingia Looks like the issue is already fixed on main, but this PR still adds the E2E test for it.

**Comment by slavingia** [comment]
Some merge conflicts to resolve
